Repository Happiness-Meta/final-front, pull requests merged in 2024-03, with the labels that each got.

#5 Update issue templates
  .github/ISSUE_TEMPLATE/issue_templete.md
Labels: docs

#7 Create pull_request_template.md
  .github/pull_request_template.md
Labels: docs

#14 [feat,refator] 기술스택 검색기능 구현 및 회원가입 페이지 리팩토링
  src/app/components/commonComponents/SignUpErrorMessage.tsx
  src/app/components/commonComponents/VisibilityEyes.tsx
  src/app/components/loginPageComponents/LoginSection.tsx
  src/app/components/signUpPageComponents/CorporateMemberSection.tsx
  src/app/components/signUpPageComponents/IndividualMemberSection.tsx
  src/app/components/signUpPageComponents/LinkToLogin.tsx
  src/app/components/signUpPageComponents/SignUpPathBtnSection.tsx
  src/app/components/signUpPageComponents/imsComponents/SignUpInputs.tsx
  src/app/components/signUpPageComponents/imsComponents/TechStackSpace.tsx
  src/app/constants/industryOptions.ts
  src/app/constants/techStacks.ts
  src/app/hooks/signUpPageHooks/useHandleSearchTechStacks.ts
  src/app/store/signUpPageStore/useSignUpPageStore.ts
  src/app/styleComponents/commonStyles/inputAndButtonAndText.ts
  src/app/styleComponents/commonStyles/keyframes.ts
  src/app/styleComponents/signUpPageStyles/errorMessageStyles.ts
  src/app/styleComponents/signUpPageStyles/techStackStyles.ts
  src/app/types/aboutSignInUp.ts
Labels: feat, docs, refactor, design

#16 design: 마이페이지 퍼블리싱
  src/app/assets/get_up_and_coding.jpg
  src/app/assets/svg/Edit.svg
  src/app/assets/svg/Home_light.svg
  src/app/assets/svg/Message_light.svg
  src/app/assets/svg/Phone_light.svg
  src/app/assets/svg/plus.svg
  src/app/constants/myPage/TechStack.tsx
  src/app/hooks/signUpPageHooks/useHandleSearchTechStacks.ts
  src/app/pages/loginPage/page.tsx
  src/app/pages/myPage/page.tsx
  src/app/styleComponents/myPageStyles/myPageProjectTitle.tsx
  src/app/styleComponents/myPageStyles/myPageStyles.tsx
Labels: design

#21 [DESIGN] 홈페이지 검색창 뷰 조정, 줄여도 메뉴바 안 깨지게 수정
  .gitignore
  package.json
  pnpm-lock.yaml
  portone.d.ts
  src/app/assets/svg/bag.svg
  src/app/assets/svg/buyticket.svg
  src/app/components/commonComponents/Projectmenu.tsx
  src/app/components/homePageComponents/HomeSearchBar.tsx
  src/app/components/homePageComponents/HomeWanted.tsx
  src/app/components/homePageComponents/JobDropDown.tsx
  src/app/hooks/homePageHooks/useDetectClose.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/pages/ticketPage/page.tsx
  src/app/store/homePageStore/useHomePageStore.ts
  src/app/store/modalStore/ticketPageStore/useModalStore.ts
  src/app/styleComponents/homePageStyles/HomePageStyles.ts
  src/app/styleComponents/homePageStyles/HomeSearchBar.ts
  src/app/types/aboutSignInUp.ts
Labels: design

#24 [design, feat] 프로젝트 기록 생성 시 환영인사 밑 동적 페이지 질문 끝났을 때 메세지 띄움, 정적 페이지 디자인…
  src/app/components/commonComponents/ProjectColoringSpace.tsx
  src/app/components/pageCreatingComponents/questions/SecondQuestion.tsx
  src/app/components/projectCreatingComponents/Footer.tsx
  src/app/components/projectCreatingComponents/buttons/NextButton.tsx
  src/app/components/projectCreatingComponents/buttons/PreviousButton.tsx
  src/app/components/projectCreatingComponents/messages/ContinueMessage.tsx
  src/app/components/projectCreatingComponents/messages/WelcomeMessage.tsx
  src/app/components/projectCreatingComponents/questions/FifthQuestion.tsx
  src/app/components/projectCreatingComponents/questions/FirstQuestion.tsx
  src/app/components/projectCreatingComponents/questions/FourthQuestion.tsx
  src/app/components/projectCreatingComponents/questions/SecondQuestion.tsx
  src/app/components/projectCreatingComponents/questions/ThirdQuestion.tsx
  src/app/components/ptpComponents/Header.tsx
  src/app/components/ptpComponents/PaintBackground.tsx
  src/app/global.css
  src/app/pages/projectCreating/page.tsx
  src/app/pages/projectCreating/projectTemplate/page.tsx
  src/app/store/commonStore/useProjectStore.ts
  src/app/styleComponents/commonStyles/keyframes.ts
  src/app/styleComponents/projectCreatingStyles/textAndEtcStyles.ts
  src/app/styleComponents/projectTemplateStyle/templateStyle.ts
  src/app/types/portfolioDto.ts
Labels: feat, design

#26 design: 워크스페이스 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/app/assets/svg/User_light.svg
  src/app/assets/svg/addIcon.svg
  src/app/assets/svg/arrow-right-small.svg
  src/app/components/myPageComponents/myPageProjectTitle.tsx
  src/app/components/workspaceComponents/WorkspaceResume.tsx
  src/app/components/workspaceComponents/WorkspaceUserProfile.tsx
  src/app/components/workspaceComponents/WorkspaeHeader.tsx
  src/app/components/workspaceComponents/workspaceProject.tsx
  src/app/constants/myPage/TechStack.tsx
  src/app/pages/myPage/page.tsx
  src/app/pages/workspacePage/page.tsx
  src/app/styleComponents/workspaceStyles/headerStyles.ts
  src/app/styleComponents/workspaceStyles/profileStylese.ts
  src/app/styleComponents/workspaceStyles/projectStyles.ts
  src/app/styleComponents/workspaceStyles/resumeStyles.ts
  src/important
Labels: design

#27 Update issue_templete.md
  .github/ISSUE_TEMPLATE/issue_templete.md
Labels: docs

#31 reactquery, axios설치/ reactquery를 위한 기본세팅 완료
  package.json
  pnpm-lock.yaml
  src/app/ReactQueryClientProvider.tsx
  src/app/components/commonComponents/ProjectColoringSpace.tsx
  src/app/components/loginPageComponents/LoginSection.tsx
  src/app/components/projectCreatingComponents/Footer.tsx
  src/app/components/ptpComponents/Header.tsx
  src/app/components/ptpComponents/PaintBackground.tsx
  src/app/components/ptpComponents/sections/ProjectDescription.tsx
  src/app/components/ptpComponents/sections/ProjectName.tsx
  src/app/components/ptpComponents/sections/ProjectPeriod.tsx
  src/app/components/ptpComponents/sections/ProjectPersonnel.tsx
  src/app/layout.tsx
  src/app/pages/loginPage/page.tsx
  src/app/pages/projectCreating/page.tsx
  src/app/pages/projectCreating/projectTemplate/page.tsx
  src/app/pages/signUpPage/page.tsx
  src/app/store/projectTemplateStore/useProjectTemplateStore.ts
  src/app/styleComponents/commonStyles/commonStyles.ts
  src/app/styleComponents/commonStyles/keyframes.ts
  src/app/styleComponents/projectCreatingStyles/buttonStyles.ts
  src/app/styleComponents/projectCreatingStyles/inputStyles.ts
  src/app/styleComponents/projectCreatingStyles/textAndEtcStyles.ts
  src/app/styleComponents/projectTemplateStyles/ptHeaderStyles.ts
  src/app/styleComponents/projectTemplateStyles/templateStyle.ts
  src/app/types/aboutCommonComponents.ts
  src/app/types/aboutProjectTemplate.ts
  src/app/types/portfolioDto.ts
Labels: docs

#29 [design, feat] 헤더에 가이드메세지 구현, 프로젝트 템플릿 리팩토링(섹션별로 컴포넌트 나눔 60%), 헤더 버튼 …
  src/app/components/commonComponents/ProjectColoringSpace.tsx
  src/app/components/loginPageComponents/LoginSection.tsx
  src/app/components/projectCreatingComponents/Footer.tsx
  src/app/components/ptpComponents/Header.tsx
  src/app/components/ptpComponents/PaintBackground.tsx
  src/app/components/ptpComponents/sections/ProjectDescription.tsx
  src/app/components/ptpComponents/sections/ProjectName.tsx
  src/app/components/ptpComponents/sections/ProjectPeriod.tsx
  src/app/components/ptpComponents/sections/ProjectPersonnel.tsx
  src/app/pages/loginPage/page.tsx
  src/app/pages/projectCreating/page.tsx
  src/app/pages/projectCreating/projectTemplate/page.tsx
  src/app/pages/signUpPage/page.tsx
  src/app/store/projectTemplateStore/useProjectTemplateStore.ts
  src/app/styleComponents/commonStyles/commonStyles.ts
  src/app/styleComponents/commonStyles/keyframes.ts
  src/app/styleComponents/projectCreatingStyles/buttonStyles.ts
  src/app/styleComponents/projectCreatingStyles/inputStyles.ts
  src/app/styleComponents/projectCreatingStyles/textAndEtcStyles.ts
  src/app/styleComponents/projectTemplateStyles/ptHeaderStyles.ts
  src/app/styleComponents/projectTemplateStyles/templateStyle.ts
  src/app/types/aboutCommonComponents.ts
  src/app/types/aboutProjectTemplate.ts
  src/app/types/portfolioDto.ts
Labels: feat, refactor, design

#34 Build/#28 json-server 세팅
  db.json
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/app/assets/svg/chat.svg
  src/app/assets/svg/nextjs.svg
  src/app/assets/svg/reactquery.svg
  src/app/assets/svg/techStack/CSS.svg
  src/app/assets/svg/techStack/Django.svg
  src/app/assets/svg/techStack/HTML.svg
  src/app/assets/svg/techStack/JS.svg
  src/app/assets/svg/techStack/Java.svg
  src/app/assets/svg/techStack/MySQL.svg
  src/app/assets/svg/techStack/Nodejs.svg
  src/app/assets/svg/techStack/React.png
  src/app/assets/svg/techStack/Recoil.svg
  src/app/assets/svg/techStack/Spring.svg
  src/app/assets/svg/techStack/TS.svg
  src/app/assets/svg/techStack/emotion.png
  src/app/assets/svg/techStack/nextjs.svg
  src/app/assets/svg/techStack/reactquery.svg
  src/app/assets/svg/techStack/zustand.jpg
  src/app/components/workspaceComponents/WorkspaeHeader.tsx
  src/app/components/workspaceComponents/workspaceProject.tsx
  src/app/constants/mswConstansts/userPortpolio.ts
  src/app/layout.tsx
  src/app/styleComponents/workspaceStyles/projectStyles.ts
  src/app/types/portPoliosThumbnailData.tsx
  src/important
Labels: build

#32 [feat,design]로그인, 회원가입 구현 및 이에 관한 추가 디자인
  src/app/components/commonComponents/SignInUpErrorMessage.tsx
  src/app/components/commonComponents/TechStackSpace.tsx
  src/app/components/loginPageComponents/HelloMessage.tsx
  src/app/components/loginPageComponents/LoginSection.tsx
  src/app/components/projectCreatingComponents/messages/WelcomeMessage.tsx
  src/app/components/projectCreatingComponents/questions/FifthQuestion.tsx
  src/app/components/projectCreatingComponents/questions/FirstQuestion.tsx
  src/app/components/projectCreatingComponents/questions/FourthQuestion.tsx
  src/app/components/projectCreatingComponents/questions/ThirdQuestion.tsx
  src/app/components/ptpComponents/sections/ProjectMainFunction.tsx
  src/app/components/ptpComponents/sections/ProjectMyFunction.tsx
  src/app/components/signUpPageComponents/CorporateMemberSection.tsx
  src/app/components/signUpPageComponents/IndividualMemberSection.tsx
  src/app/components/signUpPageComponents/WelcomeMessage.tsx
  src/app/components/signUpPageComponents/componentsForBoth/SignUpInputs.tsx
  src/app/pages/loginPage/page.tsx
  src/app/pages/projectCreating/page.tsx
  src/app/pages/projectCreating/projectTemplate/page.tsx
  src/app/pages/signUpPage/page.tsx
  src/app/store/loginPageStore/useLoginPageStore.ts
  src/app/store/projectTemplateStore/useTemplateInputStore.ts
  src/app/store/signUpPageStore/useSignUpPageStore.ts
  src/app/styleComponents/commonStyles/commonStyles.ts
  src/app/styleComponents/commonStyles/signInUpMsgStyles.ts
  src/app/styleComponents/signUpPageStyles/errorMessageStyles.ts
  src/app/styleComponents/signUpPageStyles/signUpPageStyles.ts
  src/app/types/aboutCommonComponents.ts
  src/app/types/aboutSignInUp.ts
  src/app/types/userDto.ts
Labels: feat, refactor, design

#38 [feat, bugfix, refactor] 프로젝트 템플릿 구현 기능 통합, 구현기능 2개 이상일때 상태담기 동작 안되는 …
  src/app/assets/oAuth/google.svg
  src/app/assets/oAuth/kakao.svg
  src/app/assets/svg/delete.svg
  src/app/components/commonComponents/ProjectColoringSpace.tsx
  src/app/components/commonComponents/VisibilityEyes.tsx
  src/app/components/loginPageComponents/OAuthSection.tsx
  src/app/components/projectCreatingComponents/StepViewer.tsx
  src/app/components/projectCreatingComponents/messages/WelcomeMessage.tsx
  src/app/components/ptpComponents/Header.tsx
  src/app/components/ptpComponents/PaintBackground.tsx
  src/app/components/ptpComponents/sections/ProjectDescription.tsx
  src/app/components/ptpComponents/sections/ProjectFunction.tsx
  src/app/components/ptpComponents/sections/ProjectLink.tsx
  src/app/components/ptpComponents/sections/ProjectMainFunction.tsx
  src/app/components/ptpComponents/sections/ProjectMyFunction.tsx
  src/app/components/ptpComponents/sections/ProjectName.tsx
  src/app/components/ptpComponents/sections/ProjectPeriod.tsx
  src/app/components/ptpComponents/sections/ProjectPersonnel.tsx
  src/app/components/ptpComponents/sections/ProjectProblem.tsx
  src/app/components/ptpComponents/sections/ProjectTakeaway.tsx
  src/app/components/signUpPageComponents/componentsForBoth/SignUpInputs.tsx
  src/app/pages/projectCreating/page.tsx
  src/app/pages/projectCreating/projectTemplate/page.tsx
  src/app/store/projectTemplateStore/useProjectTemplateStore.ts
  src/app/store/projectTemplateStore/useTemplateInputStore.ts
  src/app/styleComponents/commonStyles/keyframes.ts
  src/app/styleComponents/projectCreatingStyles/textAndEtcStyles.ts
  src/app/styleComponents/projectTemplateStyles/ptHeaderStyles.ts
  src/app/styleComponents/projectTemplateStyles/templateStyle.ts
  src/app/types/aboutProjectTemplate.ts
  src/app/types/portfolioDto.ts
Labels: feat, fix, refactor, design

#41 [refactor, design] techStackSpace 컴포넌트 prop 한개로 줄임 및 디자인 변경, signUpin…
  src/app/assets/svg/delete2.svg
  src/app/assets/svg/minimize.svg
  src/app/components/commonComponents/SignInUpErrorMessage.tsx
  src/app/components/commonComponents/TechStackSpace.tsx
  src/app/components/ptpComponents/Header.tsx
  src/app/components/ptpComponents/sections/ProjectFunction.tsx
  src/app/components/ptpComponents/sections/ProjectLink.tsx
  src/app/components/ptpComponents/sections/ProjectProblem.tsx
  src/app/components/ptpComponents/sections/ProjectTechStack.tsx
  src/app/components/signUpPageComponents/CorporateMemberSection.tsx
  src/app/components/signUpPageComponents/IndividualMemberSection.tsx
  src/app/components/signUpPageComponents/componentsForBoth/SignUpInputs.tsx
  src/app/constants/techStacks.ts
  src/app/global.css
  src/app/pages/projectCreating/projectTemplate/page.tsx
  src/app/store/projectTemplateStore/useProjectFunctionStore.ts
  src/app/store/projectTemplateStore/useProjectLinkStore.ts
  src/app/store/projectTemplateStore/useProjectProblemStore.ts
  src/app/store/projectTemplateStore/useTemplateInputStore.ts
  src/app/store/signUpPageStore/useSignUpPageStore.ts
  src/app/styleComponents/commonStyles/inputAndButtonAndText.ts
  src/app/styleComponents/commonStyles/keyframes.ts
  src/app/styleComponents/commonStyles/techStackSpaceStyles.ts
  src/app/styleComponents/projectCreatingStyles/buttonStyles.ts
  src/app/styleComponents/projectCreatingStyles/textAndEtcStyles.ts
  src/app/styleComponents/projectTemplateStyles/ptHeaderStyles.ts
  src/app/styleComponents/projectTemplateStyles/templateStyle.ts
  src/app/styleComponents/signUpPageStyles/signUpPageStyles.ts
  src/app/types/aboutCommonComponents.ts
  src/app/types/aboutSignInUp.ts
Labels: feat, refactor, design

#36 Design: 티켓 구매 페이지 뷰 작업, 구매 연결(로컬)
  package.json
  pnpm-lock.yaml
  portone.d.ts
  src/app/assets/svg/paletteTicketPicture.svg
  src/app/assets/svg/qrcode.svg
  src/app/components/commonComponents/Projectmenu.tsx
  src/app/components/homePageComponents/HomeSearchBar.tsx
  src/app/components/homePageComponents/MainArticleRightHappiness.tsx
  src/app/constants/orderProducts.ts
  src/app/page.tsx
  src/app/pages/myPage/cancelMembership/page.tsx
  src/app/pages/ticketPage/page.tsx
  src/app/store/homePageStore/useHomePageTechStore.ts
  src/app/styleComponents/homePageStyles/HomeSearchBar.ts
  src/app/styleComponents/ticketPagestyles/ticketPageStyles.ts
Labels: feat, design

#43 feat: workspace 페이지 UI 완료
  db.json
  src/app/assets/svg/Trash.svg
  src/app/assets/svg/techStack/React.png
  src/app/assets/svg/techStack/emotion.png
  src/app/assets/svg/techStack/emotion.svg
  src/app/assets/svg/techStack/javascript.svg
  src/app/assets/svg/techStack/react.svg
  src/app/assets/svg/techStack/typescript.svg
  src/app/assets/svg/techStack/zustand.jpg
  src/app/assets/svg/techStack/zustand.svg
  src/app/components/myPageComponents/myPageProjectTitle.tsx
  src/app/components/workspaceComponents/WorkspaeHeader.tsx
  src/app/components/workspaceComponents/workspaceProject.tsx
  src/app/constants/mswConstansts/userPortpolio.ts
  src/app/pages/myPage/page.tsx
  src/app/pages/workspacePage/page.tsx
  src/app/styleComponents/myPageStyles/myPageStyles.tsx
  src/app/styleComponents/workspaceStyles/headerStyles.ts
  src/app/styleComponents/workspaceStyles/profileStylese.ts
  src/app/styleComponents/workspaceStyles/projectStyles.ts
  src/app/styleComponents/workspaceStyles/resumeStyles.ts
  src/app/types/aboutMypage.ts
  src/app/types/aboutPortPoliosThumbnailData.tsx
  src/app/types/portfolioDto.ts
Labels: feat, design

#44 [feat, design]프로젝트 템플릿 input 자동완성 끔, 회원가입에 주소/전화번호 input 추가, 회원가입 깨진 …
  src/app/components/commonComponents/HeaderNo1.tsx
  src/app/components/commonComponents/PositionSpace.tsx
  src/app/components/commonComponents/ProjectColoringSpace.tsx
  src/app/components/commonComponents/SignInUpErrorMessage.tsx
  src/app/components/commonComponents/TechStackSpace.tsx
  src/app/components/commonComponents/VisibilityEyes.tsx
  src/app/components/loginPageComponents/LoginSection.tsx
  src/app/components/projectCreatingComponents/questions/FifthQuestion.tsx
  src/app/components/projectCreatingComponents/questions/FirstQuestion.tsx
  src/app/components/projectCreatingComponents/questions/FourthQuestion.tsx
  src/app/components/projectCreatingComponents/questions/SecondQuestion.tsx
  src/app/components/projectCreatingComponents/questions/ThirdQuestion.tsx
  src/app/components/ptpComponents/PaintBackground.tsx
  src/app/components/ptpComponents/sections/ProjectDescription.tsx
  src/app/components/ptpComponents/sections/ProjectFunction.tsx
  src/app/components/ptpComponents/sections/ProjectLink.tsx
  src/app/components/ptpComponents/sections/ProjectName.tsx
  src/app/components/ptpComponents/sections/ProjectPeriod.tsx
  src/app/components/ptpComponents/sections/ProjectPersonnel.tsx
  src/app/components/ptpComponents/sections/ProjectProblem.tsx
  src/app/components/ptpComponents/sections/ProjectTakeaway.tsx
  src/app/components/signUpPageComponents/CorporateMemberSection.tsx
  src/app/components/signUpPageComponents/IndividualMemberSection.tsx
  src/app/components/signUpPageComponents/componentsForIndiCorp/AddressAndPhoneNum.tsx
  src/app/components/signUpPageComponents/componentsForIndiCorp/SignUpInputs.tsx
  src/app/hooks/signUpPageHooks/useHandlePwVerCheck.tsx
  src/app/hooks/signUpPageHooks/useHandleSearchTechStacks.tsx
  src/app/pages/loginPage/page.tsx
  src/app/pages/projectCreating/page.tsx
  src/app/pages/projectCreating/projectTemplate/page.tsx
  src/app/pages/projectView/page.tsx
  src/app/pages/signUpPage/page.tsx
  src/app/store/commonStore/useProjectStore.ts
  src/app/store/projectTemplateStore/useProjectFunctionStore.ts
  src/app/store/projectTemplateStore/useProjectLinkStore.ts
  src/app/store/projectTemplateStore/useProjectProblemStore.ts
  src/app/styleComponents/commonStyles/inputAndButtonAndText.ts
  src/app/styleComponents/projectTemplateStyles/templateStyle.ts
  src/app/styleComponents/signUpPageStyles/signUpPageStyles.ts
  src/app/types/aboutSignInUp.ts
  src/app/types/portfolioDto.ts
  src/app/types/userDto.ts
  src/app/utils/useAxiosWithAuth.ts
Labels: feat, design

#47 design: myPage 리퍼블리싱
  src/app/assets/svg/myPageBackground.svg
  src/app/components/myPageComponents/myPageProjectTitle.tsx
  src/app/components/workspaceComponents/WorkspaceResume.tsx
  src/app/components/workspaceComponents/workspaceProject.tsx
  src/app/hooks/myPageHooks/useGetData.tsx
  src/app/pages/myPage/page.tsx
  src/app/pages/workspacePage/page.tsx
  src/app/styleComponents/myPageStyles/myPageStyles.tsx
  src/app/types/aboutMypage.ts
  src/app/types/aboutWorkspace.ts
  src/app/types/portfolioDto.ts
Labels: feat, design

#48 [feat, style] false가 undefined인 얘들 삼항연산자에서 논리연산자로 바꿈, 법인회원 회원가입 통신 완료, 로그인…
  src/app/components/commonComponents/HeaderNo1.tsx
  src/app/components/commonComponents/PositionSpace.tsx
  src/app/components/commonComponents/ProjectTitle.tsx
  src/app/components/commonComponents/TechStackSpace.tsx
  src/app/components/loginPageComponents/LoginSection.tsx
  src/app/components/projectCreatingComponents/StepViewer.tsx
  src/app/components/ptpComponents/sections/ProjectFunction.tsx
  src/app/components/ptpComponents/sections/ProjectLink.tsx
  src/app/components/ptpComponents/sections/ProjectProblem.tsx
  src/app/components/signUpPageComponents/CorporateMemberSection.tsx
  src/app/components/signUpPageComponents/IndividualMemberSection.tsx
  src/app/components/signUpPageComponents/componentsForIndiCorp/AddressAndPhoneNum.tsx
  src/app/pages/loginPage/page.tsx
  src/app/pages/projectCreating/page.tsx
  src/app/pages/signUpPage/page.tsx
  src/app/styleComponents/commonStyles/inputAndButtonAndText.ts
  src/app/styleComponents/loginPageStyles/loginPageStyles.ts
  src/app/types/aboutSignInUp.ts
  src/app/types/userDto.ts
Labels: feat, style

#51 design: 기업용 UI 구성
  db.json
  src/app/assets/svg/Address.svg
  src/app/assets/svg/mail.svg
  src/app/assets/svg/phone.svg
  src/app/components/workspaceComponents/WorkspaeHeader.tsx
  src/app/components/workspaceComponents/workspaceProject.tsx
  src/app/hooks/myPageHooks/useGetData.tsx
  src/app/pages/myPage/page.tsx
  src/app/pages/workspacePage/page.tsx
  src/app/styleComponents/myPageStyles/myPageStyles.tsx
  src/app/types/aboutMypage.ts
Labels: design

#53 [design, feat] projectView 페이지 뷰 및 로직 완성/리팩토링 10%, 회원가입 디자인 오류 고침
  src/app/components/commonComponents/HeaderNo1.tsx
  src/app/components/commonComponents/PositionSpace.tsx
  src/app/components/commonComponents/TechStackSpace.tsx
  src/app/components/commonComponents/buttons/WorkspaceBtn.tsx
  src/app/components/loginPageComponents/LoginSection.tsx
  src/app/components/projectViewComponents/Header.tsx
  src/app/components/projectViewComponents/sections/ProjectName.tsx
  src/app/components/signUpPageComponents/IndividualMemberSection.tsx
  src/app/components/signUpPageComponents/SignUpPathBtnSection.tsx
  src/app/global.css
  src/app/page.tsx
  src/app/pages/projectCreating/projectTemplate/page.tsx
  src/app/pages/projectView/[id]/page.tsx
  src/app/pages/projectView/page.tsx
  src/app/pages/signUpPage/page.tsx
  src/app/styleComponents/commonStyles/inputAndButtonAndText.ts
  src/app/styleComponents/commonStyles/techStackSpaceStyles.ts
  src/app/styleComponents/loginPageStyles/loginPageStyles.ts
  src/app/styleComponents/projectTemplateStyles/templateStyle.ts
  src/app/styleComponents/projectViewStyles.ts/projectViewStyles.ts
  src/app/styleComponents/signUpPageStyles/signUpPageStyles.ts
  src/app/types/aboutProjectView.ts
  src/app/utils/useAxiosWithAuth.ts
Labels: feat, design
